# ./Taskfile.yaml
# See: https://taskfile.dev/api/

version: "3"

tasks:
  default: # If no command is given, default one will run
    cmds:
      - task: generate
  generate:  ## Command to generate
    aliases: ## Aliases of commands
      - gen
    desc: "Generate code from proto files"
    cmds:  ## Commands in terminal
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative